[build]
  command   = "npm run build"
  publish   = ".next"
  functions = "netlify/functions"

[dev]
  command    = "npm run dev:web"
  functions  = "netlify/functions"
  targetPort = 3000

[[redirects]]
  from   = "/api/*"
  to     = "/.netlify/functions/:splat"
  status = 200
  force  = true
